name: php
on:
  pull_request:
  push:
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.1', "8.2"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer

    - name: Install dependencies
      run: composer update --no-ansi --no-interaction --no-progress

    - name: Collect code coverage with phpunit
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Send code coverage report to Codecov.io
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
